### PR TITLE
Change PrimarkKeys To Guid

### PR DESCRIPTION
**Pull request by htve**
1. Modify the primary key for all tables to guid;
2. Updated Nuget packages.

### CODE REVIEW

**Comment by kouweizhong** [comment]
I agree to the above said!

**Comment by hikalkan** [comment]
Hi,

@htve Thank you very much for your huge effort. But it's a big breaking change and we get much reaction if we merge it. We should discuss and think on it more.

**Comment by RGBKnights** [comment]
We faced a simular issue in our project a while ago.

GUID Pros

- Unique across every table, every database, every server
- Allows easy merging of records from different databases
- Allows easy distribution of databases across multiple servers
- You can generate IDs anywhere, instead of having to roundtrip to the database
- Most replication scenarios require GUID columns anyway

GUID Cons

- It is a whopping 4 times larger than the traditional 4-byte index value; this can have serious performance and storage implications if you're not careful
- Cumbersome to debug where userid='{BAE7DF4-DDF-3RG-5TY3E3RF456AS10}'
- The generated GUIDs should be partially sequential for best performance (eg, newsequentialid() on SQL 2005) and to enable use of clustered indexes

In the end having the choice would nice when settting up a new project would ne nice.

**Comment by htve** [comment]
@RGBKnights 
Please go to
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/979
This is related to the two PR.

**Pull request closed without merging**
