### PR TITLE
Update ApplicationLanguage.cs

### PR DESCRIPTION
**Pull request by ghost**
for change output view direction when change language.

### CODE REVIEW

**Comment by AEChabok** [comment]
first edit LanguageInfo in abp then edit it and rebuild

**Comment by hikalkan** [comment]
We just use a simple code to check if current culture is RTL:

````C#
    public static class CultureHelper
    {
        public static bool IsRtl
        {
            get { return Thread.CurrentThread.CurrentUICulture.TextInfo.IsRightToLeft; }
        }
    }
````

So, .net already provides a simple way of calculating it. Why we store a calculateable value in the database?

**Comment by AEChabok** [comment]
I Like It, Thanks, but for example, in google translate page, current language and final language are not same.

this code return current cultures, i need current and final language in same time.

**Comment by hikalkan** [comment]
This was just an example of getting RTL. If you know the culture code (you know it since language definition contains it) you can do that:

````C#
var isRtl = new CultureInfo("tr-TR").TextInfo.IsRightToLeft;
````

**Pull request closed without merging**
